[unit]
description = "Session management (depends on tty plugin)"

[[service]]
name = "user_login"
description = "Login service (managed by tty plugin)"
run.exec = "/usr/bin/syssess"
run.args = ["login"]
restart = false
start-on = [{ facet = "seat:login_required" }]
transport = { id = "env", options = ["RIND_LOGIN_TTY=facet:$/seat"] }
branching = { source = "seat:login_required", key = "seat", max-instances = 16 }

[[service]]
name = "user_shell"
description = "Shell service (managed by rind internals)"
run.exec = "/usr/bin/syssess"
run.args = ["shell"]
restart = false
start-on = [{ facet = "rind:user_session" }]
transport = { id = "env", options = ["RIND_USER_ACTIVE=facet:$"] }
branching = { source = "rind:user_session", key = "seat", max-instances = 16, except = ["facet:tty:taken"] }
